title: 'Overrun Organization'
description: "Overrun Organization's Github Pages"
lang: zh-CN
show_downloads: false

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

theme: jekyll-theme-cayman

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"